version: '3'
services:
  app:
    build: .
    tty: true
    stdin_open: true
    shm_size: 512
    ports:
      - "3000:3000"
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
volumes:
  app:
    driver: "local"
